### ISSUE TITLE
Volt 2.1.1 + Primefaces 6.0.4 Javascript Error

### ISSUE THREAD

**Issue by lcanalesmayo** [primefaces/layouts#109]
Hi,

When I use "menu" component from Volt template I got this Javascript Error:

Widget not available: Volt

This happens with Volt 2.1.1 an Primefaces 6.X. This doesn't happen with Volt 2.1 and Primefaces 5.3.17.

Forum link: http://forum.primefaces.org/viewtopic.php?f=29&t=47074&p=146154#p146154

Thanks in advance.

**Comment by mertsincan** [comment]
I think this issue is fixed on next version; https://github.com/primefaces/layouts/issues/106
In next version, please use PF('Volt').method() instead of Volt.method() in p:menuitems or your custom JS methods.

**Comment by lcanalesmayo** [comment]
Hi,

I'm not using Volt.method(), this error happens when I use a menu component from Volt template

Regards

**Comment by lcanalesmayo** [comment]
Hi,

this error still happens with Volt 2.1.2 and Primefaces 6.0.6.

Could you reopen this issue?

Thanks.

**Comment by lcanalesmayo** [comment]
Hi,

I think error is in VoltMenuRenderer class:

@Override
    protected void encodeScript(FacesContext context, AbstractMenu abstractMenu) throws IOException {     
        VoltMenu menu = (VoltMenu) abstractMenu;
        String clientId = menu.getClientId(context);
        WidgetBuilder wb = getWidgetBuilder(context);
        wb.initWithDomReady("Volt", menu.resolveWidgetVar(), clientId).finish();
    }

Thanks.

**Comment by mertsincan** [comment]
Please change the following files with new files;
- layout.js
- VoltMenuRenderer.java
- VoltMenu.java

**Comment by lcanalesmayo** [comment]
It worked!!

Thanks.
